//===- CoreMappingPass.cpp - Map spatial tiles to NPU cores ----*- C++ -*-===//
//
// Wraps spatial tiling loop bodies with npu.core_execute regions,
// assigning each tile iteration to a specific core.
//
// For outermost scf.for loops (generated by spatial tiling), the
// core ID is computed as (induction_var - lower_bound) / step.
// Currently inserts the core_id computation and emits remarks;
// full wrapping into npu.core_execute will be added later.
//
//===----------------------------------------------------------------------===//

#include "npu/Transforms/Passes.h"
#include "npu/Dialect/NPU/NPUDialect.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/SCF/IR/SCF.h"

namespace npu {
#define GEN_PASS_DEF_NPUCOREMAPPING
#include "npu/Transforms/Passes.h.inc"
} // namespace npu

using namespace mlir;
using namespace npu;

namespace {

struct NPUCoreMappingPass
    : public npu::impl::NPUCoreMappingBase<NPUCoreMappingPass> {
  using NPUCoreMappingBase::NPUCoreMappingBase;

  void runOnOperation() override {
    auto funcOp = getOperation();

    // Collect outermost scf.for loops (not nested inside another scf.for).
    SmallVector<scf::ForOp> outerLoops;
    funcOp.walk([&](scf::ForOp forOp) {
      if (!forOp->getParentOfType<scf::ForOp>())
        outerLoops.push_back(forOp);
    });

    for (auto forOp : outerLoops) {
      // Only handle loops with constant bounds and step.
      auto lb =
          forOp.getLowerBound().getDefiningOp<arith::ConstantIndexOp>();
      auto step =
          forOp.getStep().getDefiningOp<arith::ConstantIndexOp>();
      if (!lb || !step)
        continue;

      // Insert core_id computation at the beginning of the loop body:
      //   core_id = (iv - lb) / step
      OpBuilder builder(forOp.getBody(), forOp.getBody()->begin());
      Location loc = forOp.getLoc();
      Value iv = forOp.getInductionVar();
      Value lbVal =
          arith::ConstantIndexOp::create(builder, loc, lb.value());
      Value stepVal =
          arith::ConstantIndexOp::create(builder, loc, step.value());
      Value offset = arith::SubIOp::create(builder, loc, iv, lbVal);
      Value coreId = arith::DivUIOp::create(builder, loc, offset, stepVal);
      Value coreIdI64 = arith::IndexCastOp::create(
          builder, loc, builder.getI64Type(), coreId);

      // Mark the core_id value so downstream passes can find it.
      coreIdI64.getDefiningOp()->setAttr("npu.core_id",
                                         builder.getUnitAttr());

      // Emit remark for diagnostics / testing.
      forOp->emitRemark("core mapping: loop mapped to cores");
    }
  }
};

} // namespace
